//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIGFISH_БД
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvancePayPackers
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateAdv { get; set; }
        public string FIO { get; set; }
        public Nullable<double> AdvancePay { get; set; }
    
        public virtual Packers Packers { get; set; }
    }
}
