//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIGFISH_БД
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorArticles
    {
        public string ColorArticle { get; set; }
        public string Article { get; set; }
    
        public virtual Articles Articles { get; set; }
    }
}
