//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIGFISH_БД
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReport
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DatePack { get; set; }
        public string FIO { get; set; }
        public string StorageName { get; set; }
        public Nullable<double> FinePacks { get; set; }
        public Nullable<double> Packs { get; set; }
        public System.DateTime DateFoundry { get; set; }
        public Nullable<double> Packs2 { get; set; }
        public Nullable<double> FinePacksFoundry { get; set; }
        public string FIO_Foundry { get; set; }
        public string Number_Ved { get; set; }
        public string ArticlePack { get; set; }
        public string ArticleFoundry { get; set; }
    
        public virtual Articles Articles { get; set; }
        public virtual Articles Articles1 { get; set; }
        public virtual Foundry Foundry { get; set; }
        public virtual Packers Packers { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
