//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIGFISH_БД
{
    using System;
    using System.Collections.Generic;
    
    public partial class DopFoundry
    {
        public System.DateTime DateDop { get; set; }
        public int IdDop { get; set; }
        public string FIO_Foundry { get; set; }
        public string Name_Dop { get; set; }
        public int PriceForOne { get; set; }
        public int Colvo { get; set; }
        public string IdVed { get; set; }
    
        public virtual Foundry Foundry { get; set; }
        public virtual Naim_Dop Naim_Dop { get; set; }
    }
}
