//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIGFISH_БД
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BigFishBDEntities : DbContext
    {
        public BigFishBDEntities()
            : base("name=BigFishBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ColorArticles> ColorArticles { get; set; }
        public virtual DbSet<Foundry> Foundry { get; set; }
        public virtual DbSet<Packers> Packers { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<User1> User1 { get; set; }
        public virtual DbSet<Articles> Articles { get; set; }
        public virtual DbSet<DailyReport> DailyReport { get; set; }
        public virtual DbSet<Naim_Dop> Naim_Dop { get; set; }
        public virtual DbSet<DopFoundry> DopFoundry { get; set; }
        public virtual DbSet<DopPackers> DopPackers { get; set; }
        public virtual DbSet<AdvancePayFoundry> AdvancePayFoundry { get; set; }
        public virtual DbSet<AdvancePayPackers> AdvancePayPackers { get; set; }
    }
}
